/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 adventurers.glb --types --shadows 
Author: Nick Ladd (https://sketchfab.com/Nicktheladd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/quill-adventurers-at-rest-ad346009f1654a968784d67acf52eac8
Title: Quill - Adventurers at Rest
*/

import * as THREE from "three";
import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type ActionName = "Object_0";

interface GLTFAction extends THREE.AnimationClip {
	name: ActionName;
}

type GLTFResult = GLTF & {
	nodes: {
		Object_5: THREE.Mesh;
		Object_7: THREE.Mesh;
		Object_9: THREE.Mesh;
		Object_11: THREE.Mesh;
		Object_13: THREE.Mesh;
		Object_15: THREE.Mesh;
		Object_17: THREE.Mesh;
		Object_19: THREE.Mesh;
		Object_21: THREE.Mesh;
		Object_23: THREE.Mesh;
		Object_25: THREE.Mesh;
		Object_27: THREE.Mesh;
		Object_29: THREE.Mesh;
		Object_31: THREE.Mesh;
		Object_33: THREE.Mesh;
		Object_35: THREE.Mesh;
		Object_37: THREE.Mesh;
		Object_39: THREE.Mesh;
		Object_41: THREE.Mesh;
		Object_43: THREE.Mesh;
		Object_45: THREE.Mesh;
		Object_49: THREE.Mesh;
		Object_51: THREE.Mesh;
		Object_53: THREE.Mesh;
		Object_55: THREE.Mesh;
		Object_57: THREE.Mesh;
		Object_59: THREE.Mesh;
		Object_61: THREE.Mesh;
		Object_63: THREE.Mesh;
		Object_65: THREE.Mesh;
		Object_67: THREE.Mesh;
		Object_69: THREE.Mesh;
		Object_71: THREE.Mesh;
		Object_73: THREE.Mesh;
		Object_75: THREE.Mesh;
		Object_77: THREE.Mesh;
		Object_79: THREE.Mesh;
		Object_81: THREE.Mesh;
		Object_83: THREE.Mesh;
		Object_85: THREE.Mesh;
		Object_87: THREE.Mesh;
		Object_89: THREE.Mesh;
		Object_93: THREE.Mesh;
		Object_95: THREE.Mesh;
		Object_97: THREE.Mesh;
		Object_99: THREE.Mesh;
		Object_101: THREE.Mesh;
		Object_103: THREE.Mesh;
		Object_105: THREE.Mesh;
		Object_107: THREE.Mesh;
		Object_109: THREE.Mesh;
		Object_111: THREE.Mesh;
		Object_113: THREE.Mesh;
		Object_115: THREE.Mesh;
		Object_117: THREE.Mesh;
		Object_119: THREE.Mesh;
		Object_121: THREE.Mesh;
		Object_123: THREE.Mesh;
		Object_125: THREE.Mesh;
		Object_127: THREE.Mesh;
		Object_129: THREE.Mesh;
		Object_131: THREE.Mesh;
		Object_133: THREE.Mesh;
		Object_137: THREE.Mesh;
		Object_139: THREE.Mesh;
		Object_141: THREE.Mesh;
		Object_143: THREE.Mesh;
		Object_145: THREE.Mesh;
		Object_147: THREE.Mesh;
		Object_149: THREE.Mesh;
		Object_151: THREE.Mesh;
		Object_153: THREE.Mesh;
		Object_155: THREE.Mesh;
		Object_157: THREE.Mesh;
		Object_159: THREE.Mesh;
		Object_161: THREE.Mesh;
		Object_163: THREE.Mesh;
		Object_165: THREE.Mesh;
		Object_167: THREE.Mesh;
		Object_169: THREE.Mesh;
		Object_171: THREE.Mesh;
		Object_173: THREE.Mesh;
		Object_175: THREE.Mesh;
		Object_177: THREE.Mesh;
		Object_181: THREE.Mesh;
		Object_183: THREE.Mesh;
		Object_185: THREE.Mesh;
		Object_187: THREE.Mesh;
		Object_189: THREE.Mesh;
		Object_191: THREE.Mesh;
		Object_193: THREE.Mesh;
		Object_195: THREE.Mesh;
		Object_197: THREE.Mesh;
		Object_199: THREE.Mesh;
		Object_201: THREE.Mesh;
		Object_203: THREE.Mesh;
		Object_205: THREE.Mesh;
		Object_207: THREE.Mesh;
		Object_209: THREE.Mesh;
		Object_211: THREE.Mesh;
		Object_213: THREE.Mesh;
		Object_215: THREE.Mesh;
		Object_217: THREE.Mesh;
		Object_219: THREE.Mesh;
		Object_221: THREE.Mesh;
		Object_225: THREE.Mesh;
		Object_227: THREE.Mesh;
		Object_229: THREE.Mesh;
		Object_231: THREE.Mesh;
		Object_233: THREE.Mesh;
		Object_235: THREE.Mesh;
		Object_237: THREE.Mesh;
		Object_239: THREE.Mesh;
		Object_241: THREE.Mesh;
		Object_243: THREE.Mesh;
		Object_245: THREE.Mesh;
		Object_247: THREE.Mesh;
		Object_249: THREE.Mesh;
		Object_251: THREE.Mesh;
		Object_253: THREE.Mesh;
		Object_255: THREE.Mesh;
		Object_257: THREE.Mesh;
		Object_259: THREE.Mesh;
		Object_261: THREE.Mesh;
		Object_263: THREE.Mesh;
		Object_265: THREE.Mesh;
		Object_269: THREE.Mesh;
		Object_271: THREE.Mesh;
		Object_273: THREE.Mesh;
		Object_275: THREE.Mesh;
		Object_277: THREE.Mesh;
		Object_279: THREE.Mesh;
		Object_281: THREE.Mesh;
		Object_283: THREE.Mesh;
		Object_285: THREE.Mesh;
		Object_287: THREE.Mesh;
		Object_289: THREE.Mesh;
		Object_291: THREE.Mesh;
		Object_293: THREE.Mesh;
		Object_295: THREE.Mesh;
		Object_297: THREE.Mesh;
		Object_299: THREE.Mesh;
		Object_301: THREE.Mesh;
		Object_303: THREE.Mesh;
		Object_305: THREE.Mesh;
		Object_307: THREE.Mesh;
		Object_309: THREE.Mesh;
		Object_313: THREE.Mesh;
		Object_315: THREE.Mesh;
		Object_317: THREE.Mesh;
		Object_319: THREE.Mesh;
		Object_321: THREE.Mesh;
		Object_323: THREE.Mesh;
		Object_325: THREE.Mesh;
		Object_327: THREE.Mesh;
		Object_329: THREE.Mesh;
		Object_331: THREE.Mesh;
		Object_333: THREE.Mesh;
		Object_335: THREE.Mesh;
		Object_337: THREE.Mesh;
		Object_339: THREE.Mesh;
		Object_341: THREE.Mesh;
		Object_343: THREE.Mesh;
		Object_345: THREE.Mesh;
		Object_347: THREE.Mesh;
		Object_349: THREE.Mesh;
		Object_351: THREE.Mesh;
		Object_353: THREE.Mesh;
		Object_357: THREE.Mesh;
		Object_359: THREE.Mesh;
		Object_361: THREE.Mesh;
		Object_363: THREE.Mesh;
		Object_365: THREE.Mesh;
		Object_367: THREE.Mesh;
		Object_369: THREE.Mesh;
		Object_371: THREE.Mesh;
		Object_373: THREE.Mesh;
		Object_375: THREE.Mesh;
		Object_377: THREE.Mesh;
		Object_379: THREE.Mesh;
		Object_381: THREE.Mesh;
		Object_383: THREE.Mesh;
		Object_385: THREE.Mesh;
		Object_387: THREE.Mesh;
		Object_389: THREE.Mesh;
		Object_391: THREE.Mesh;
		Object_393: THREE.Mesh;
		Object_395: THREE.Mesh;
		Object_397: THREE.Mesh;
		Object_401: THREE.Mesh;
		Object_403: THREE.Mesh;
		Object_405: THREE.Mesh;
		Object_407: THREE.Mesh;
		Object_409: THREE.Mesh;
		Object_411: THREE.Mesh;
		Object_413: THREE.Mesh;
		Object_415: THREE.Mesh;
		Object_417: THREE.Mesh;
		Object_419: THREE.Mesh;
		Object_421: THREE.Mesh;
		Object_423: THREE.Mesh;
		Object_425: THREE.Mesh;
		Object_427: THREE.Mesh;
		Object_429: THREE.Mesh;
		Object_431: THREE.Mesh;
		Object_433: THREE.Mesh;
		Object_435: THREE.Mesh;
		Object_437: THREE.Mesh;
		Object_439: THREE.Mesh;
		Object_441: THREE.Mesh;
		Object_445: THREE.Mesh;
		Object_447: THREE.Mesh;
		Object_449: THREE.Mesh;
		Object_451: THREE.Mesh;
		Object_453: THREE.Mesh;
		Object_455: THREE.Mesh;
		Object_457: THREE.Mesh;
		Object_459: THREE.Mesh;
		Object_461: THREE.Mesh;
		Object_463: THREE.Mesh;
		Object_465: THREE.Mesh;
		Object_467: THREE.Mesh;
		Object_469: THREE.Mesh;
		Object_471: THREE.Mesh;
		Object_473: THREE.Mesh;
		Object_475: THREE.Mesh;
		Object_477: THREE.Mesh;
		Object_479: THREE.Mesh;
		Object_481: THREE.Mesh;
		Object_483: THREE.Mesh;
		Object_485: THREE.Mesh;
		Object_489: THREE.Mesh;
		Object_491: THREE.Mesh;
		Object_493: THREE.Mesh;
		Object_495: THREE.Mesh;
		Object_497: THREE.Mesh;
		Object_499: THREE.Mesh;
		Object_501: THREE.Mesh;
		Object_503: THREE.Mesh;
		Object_505: THREE.Mesh;
		Object_507: THREE.Mesh;
		Object_509: THREE.Mesh;
		Object_511: THREE.Mesh;
		Object_513: THREE.Mesh;
		Object_515: THREE.Mesh;
		Object_517: THREE.Mesh;
		Object_519: THREE.Mesh;
		Object_521: THREE.Mesh;
		Object_523: THREE.Mesh;
		Object_525: THREE.Mesh;
		Object_527: THREE.Mesh;
		Object_529: THREE.Mesh;
		Object_533: THREE.Mesh;
		Object_535: THREE.Mesh;
		Object_537: THREE.Mesh;
		Object_539: THREE.Mesh;
		Object_541: THREE.Mesh;
		Object_543: THREE.Mesh;
		Object_545: THREE.Mesh;
		Object_547: THREE.Mesh;
		Object_549: THREE.Mesh;
		Object_551: THREE.Mesh;
		Object_553: THREE.Mesh;
		Object_555: THREE.Mesh;
		Object_557: THREE.Mesh;
		Object_559: THREE.Mesh;
		Object_561: THREE.Mesh;
		Object_563: THREE.Mesh;
		Object_565: THREE.Mesh;
		Object_567: THREE.Mesh;
		Object_569: THREE.Mesh;
		Object_571: THREE.Mesh;
		Object_573: THREE.Mesh;
		Object_577: THREE.Mesh;
		Object_579: THREE.Mesh;
		Object_581: THREE.Mesh;
		Object_583: THREE.Mesh;
		Object_585: THREE.Mesh;
		Object_587: THREE.Mesh;
		Object_589: THREE.Mesh;
		Object_591: THREE.Mesh;
		Object_593: THREE.Mesh;
		Object_595: THREE.Mesh;
		Object_597: THREE.Mesh;
		Object_599: THREE.Mesh;
		Object_601: THREE.Mesh;
		Object_603: THREE.Mesh;
		Object_605: THREE.Mesh;
		Object_607: THREE.Mesh;
		Object_609: THREE.Mesh;
		Object_611: THREE.Mesh;
		Object_613: THREE.Mesh;
		Object_615: THREE.Mesh;
		Object_617: THREE.Mesh;
	};
	materials: {
		material_0: THREE.MeshBasicMaterial;
		Material0: THREE.MeshBasicMaterial;
	};
	animations: GLTFAction[];
};

const AdventurersCamp = (props: JSX.IntrinsicElements["group"]) => {
	const group = React.useRef<THREE.Group>(null!);
	const { nodes, materials, animations } = useGLTF(
		"/adventurers.glb",
	) as GLTFResult;
	const { actions } = useAnimations(animations, group);  
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Sketchfab_Scene">
				<group
					name="Sketchfab_model"
					position={[0.033, 0.001, 0]}
					rotation={[-Math.PI / 2, -0.035, 0]}
					scale={8.333}
				>
					<group name="sketchfabtimeframe">
						<group name="Object_2" scale={0}>
							<group name="frame_13">
								<group name="Object_4">
									<mesh
										name="Object_5"
										castShadow
										receiveShadow
										geometry={nodes.Object_5.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_6">
									<mesh
										name="Object_7"
										castShadow
										receiveShadow
										geometry={nodes.Object_7.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_8">
									<mesh
										name="Object_9"
										castShadow
										receiveShadow
										geometry={nodes.Object_9.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_10">
									<mesh
										name="Object_11"
										castShadow
										receiveShadow
										geometry={nodes.Object_11.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_12">
									<mesh
										name="Object_13"
										castShadow
										receiveShadow
										geometry={nodes.Object_13.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_14">
									<mesh
										name="Object_15"
										castShadow
										receiveShadow
										geometry={nodes.Object_15.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_16">
									<mesh
										name="Object_17"
										castShadow
										receiveShadow
										geometry={nodes.Object_17.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_18">
									<mesh
										name="Object_19"
										castShadow
										receiveShadow
										geometry={nodes.Object_19.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_20">
									<mesh
										name="Object_21"
										castShadow
										receiveShadow
										geometry={nodes.Object_21.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_22">
									<mesh
										name="Object_23"
										castShadow
										receiveShadow
										geometry={nodes.Object_23.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_24">
									<mesh
										name="Object_25"
										castShadow
										receiveShadow
										geometry={nodes.Object_25.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_26">
									<mesh
										name="Object_27"
										castShadow
										receiveShadow
										geometry={nodes.Object_27.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_28">
									<mesh
										name="Object_29"
										castShadow
										receiveShadow
										geometry={nodes.Object_29.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_30">
									<mesh
										name="Object_31"
										castShadow
										receiveShadow
										geometry={nodes.Object_31.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_32">
									<mesh
										name="Object_33"
										castShadow
										receiveShadow
										geometry={nodes.Object_33.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_34">
									<mesh
										name="Object_35"
										castShadow
										receiveShadow
										geometry={nodes.Object_35.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_36">
									<mesh
										name="Object_37"
										castShadow
										receiveShadow
										geometry={nodes.Object_37.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_38">
									<mesh
										name="Object_39"
										castShadow
										receiveShadow
										geometry={nodes.Object_39.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_40">
									<mesh
										name="Object_41"
										castShadow
										receiveShadow
										geometry={nodes.Object_41.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_42">
									<mesh
										name="Object_43"
										castShadow
										receiveShadow
										geometry={nodes.Object_43.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_44">
									<mesh
										name="Object_45"
										castShadow
										receiveShadow
										geometry={nodes.Object_45.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_46" scale={0}>
							<group name="frame_12">
								<group name="Object_48">
									<mesh
										name="Object_49"
										castShadow
										receiveShadow
										geometry={nodes.Object_49.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_50">
									<mesh
										name="Object_51"
										castShadow
										receiveShadow
										geometry={nodes.Object_51.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_52">
									<mesh
										name="Object_53"
										castShadow
										receiveShadow
										geometry={nodes.Object_53.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_54">
									<mesh
										name="Object_55"
										castShadow
										receiveShadow
										geometry={nodes.Object_55.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_56">
									<mesh
										name="Object_57"
										castShadow
										receiveShadow
										geometry={nodes.Object_57.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_58">
									<mesh
										name="Object_59"
										castShadow
										receiveShadow
										geometry={nodes.Object_59.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_60">
									<mesh
										name="Object_61"
										castShadow
										receiveShadow
										geometry={nodes.Object_61.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_62">
									<mesh
										name="Object_63"
										castShadow
										receiveShadow
										geometry={nodes.Object_63.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_64">
									<mesh
										name="Object_65"
										castShadow
										receiveShadow
										geometry={nodes.Object_65.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_66">
									<mesh
										name="Object_67"
										castShadow
										receiveShadow
										geometry={nodes.Object_67.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_68">
									<mesh
										name="Object_69"
										castShadow
										receiveShadow
										geometry={nodes.Object_69.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_70">
									<mesh
										name="Object_71"
										castShadow
										receiveShadow
										geometry={nodes.Object_71.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_72">
									<mesh
										name="Object_73"
										castShadow
										receiveShadow
										geometry={nodes.Object_73.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_74">
									<mesh
										name="Object_75"
										castShadow
										receiveShadow
										geometry={nodes.Object_75.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_76">
									<mesh
										name="Object_77"
										castShadow
										receiveShadow
										geometry={nodes.Object_77.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_78">
									<mesh
										name="Object_79"
										castShadow
										receiveShadow
										geometry={nodes.Object_79.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_80">
									<mesh
										name="Object_81"
										castShadow
										receiveShadow
										geometry={nodes.Object_81.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_82">
									<mesh
										name="Object_83"
										castShadow
										receiveShadow
										geometry={nodes.Object_83.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_84">
									<mesh
										name="Object_85"
										castShadow
										receiveShadow
										geometry={nodes.Object_85.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_86">
									<mesh
										name="Object_87"
										castShadow
										receiveShadow
										geometry={nodes.Object_87.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_88">
									<mesh
										name="Object_89"
										castShadow
										receiveShadow
										geometry={nodes.Object_89.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_90" scale={0}>
							<group name="frame_11">
								<group name="Object_92">
									<mesh
										name="Object_93"
										castShadow
										receiveShadow
										geometry={nodes.Object_93.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_94">
									<mesh
										name="Object_95"
										castShadow
										receiveShadow
										geometry={nodes.Object_95.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_96">
									<mesh
										name="Object_97"
										castShadow
										receiveShadow
										geometry={nodes.Object_97.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_98">
									<mesh
										name="Object_99"
										castShadow
										receiveShadow
										geometry={nodes.Object_99.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_100">
									<mesh
										name="Object_101"
										castShadow
										receiveShadow
										geometry={nodes.Object_101.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_102">
									<mesh
										name="Object_103"
										castShadow
										receiveShadow
										geometry={nodes.Object_103.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_104">
									<mesh
										name="Object_105"
										castShadow
										receiveShadow
										geometry={nodes.Object_105.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_106">
									<mesh
										name="Object_107"
										castShadow
										receiveShadow
										geometry={nodes.Object_107.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_108">
									<mesh
										name="Object_109"
										castShadow
										receiveShadow
										geometry={nodes.Object_109.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_110">
									<mesh
										name="Object_111"
										castShadow
										receiveShadow
										geometry={nodes.Object_111.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_112">
									<mesh
										name="Object_113"
										castShadow
										receiveShadow
										geometry={nodes.Object_113.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_114">
									<mesh
										name="Object_115"
										castShadow
										receiveShadow
										geometry={nodes.Object_115.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_116">
									<mesh
										name="Object_117"
										castShadow
										receiveShadow
										geometry={nodes.Object_117.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_118">
									<mesh
										name="Object_119"
										castShadow
										receiveShadow
										geometry={nodes.Object_119.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_120">
									<mesh
										name="Object_121"
										castShadow
										receiveShadow
										geometry={nodes.Object_121.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_122">
									<mesh
										name="Object_123"
										castShadow
										receiveShadow
										geometry={nodes.Object_123.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_124">
									<mesh
										name="Object_125"
										castShadow
										receiveShadow
										geometry={nodes.Object_125.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_126">
									<mesh
										name="Object_127"
										castShadow
										receiveShadow
										geometry={nodes.Object_127.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_128">
									<mesh
										name="Object_129"
										castShadow
										receiveShadow
										geometry={nodes.Object_129.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_130">
									<mesh
										name="Object_131"
										castShadow
										receiveShadow
										geometry={nodes.Object_131.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_132">
									<mesh
										name="Object_133"
										castShadow
										receiveShadow
										geometry={nodes.Object_133.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_134" scale={0}>
							<group name="frame_10">
								<group name="Object_136">
									<mesh
										name="Object_137"
										castShadow
										receiveShadow
										geometry={nodes.Object_137.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_138">
									<mesh
										name="Object_139"
										castShadow
										receiveShadow
										geometry={nodes.Object_139.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_140">
									<mesh
										name="Object_141"
										castShadow
										receiveShadow
										geometry={nodes.Object_141.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_142">
									<mesh
										name="Object_143"
										castShadow
										receiveShadow
										geometry={nodes.Object_143.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_144">
									<mesh
										name="Object_145"
										castShadow
										receiveShadow
										geometry={nodes.Object_145.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_146">
									<mesh
										name="Object_147"
										castShadow
										receiveShadow
										geometry={nodes.Object_147.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_148">
									<mesh
										name="Object_149"
										castShadow
										receiveShadow
										geometry={nodes.Object_149.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_150">
									<mesh
										name="Object_151"
										castShadow
										receiveShadow
										geometry={nodes.Object_151.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_152">
									<mesh
										name="Object_153"
										castShadow
										receiveShadow
										geometry={nodes.Object_153.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_154">
									<mesh
										name="Object_155"
										castShadow
										receiveShadow
										geometry={nodes.Object_155.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_156">
									<mesh
										name="Object_157"
										castShadow
										receiveShadow
										geometry={nodes.Object_157.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_158">
									<mesh
										name="Object_159"
										castShadow
										receiveShadow
										geometry={nodes.Object_159.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_160">
									<mesh
										name="Object_161"
										castShadow
										receiveShadow
										geometry={nodes.Object_161.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_162">
									<mesh
										name="Object_163"
										castShadow
										receiveShadow
										geometry={nodes.Object_163.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_164">
									<mesh
										name="Object_165"
										castShadow
										receiveShadow
										geometry={nodes.Object_165.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_166">
									<mesh
										name="Object_167"
										castShadow
										receiveShadow
										geometry={nodes.Object_167.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_168">
									<mesh
										name="Object_169"
										castShadow
										receiveShadow
										geometry={nodes.Object_169.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_170">
									<mesh
										name="Object_171"
										castShadow
										receiveShadow
										geometry={nodes.Object_171.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_172">
									<mesh
										name="Object_173"
										castShadow
										receiveShadow
										geometry={nodes.Object_173.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_174">
									<mesh
										name="Object_175"
										castShadow
										receiveShadow
										geometry={nodes.Object_175.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_176">
									<mesh
										name="Object_177"
										castShadow
										receiveShadow
										geometry={nodes.Object_177.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_178" scale={0}>
							<group name="frame_9">
								<group name="Object_180">
									<mesh
										name="Object_181"
										castShadow
										receiveShadow
										geometry={nodes.Object_181.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_182">
									<mesh
										name="Object_183"
										castShadow
										receiveShadow
										geometry={nodes.Object_183.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_184">
									<mesh
										name="Object_185"
										castShadow
										receiveShadow
										geometry={nodes.Object_185.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_186">
									<mesh
										name="Object_187"
										castShadow
										receiveShadow
										geometry={nodes.Object_187.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_188">
									<mesh
										name="Object_189"
										castShadow
										receiveShadow
										geometry={nodes.Object_189.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_190">
									<mesh
										name="Object_191"
										castShadow
										receiveShadow
										geometry={nodes.Object_191.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_192">
									<mesh
										name="Object_193"
										castShadow
										receiveShadow
										geometry={nodes.Object_193.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_194">
									<mesh
										name="Object_195"
										castShadow
										receiveShadow
										geometry={nodes.Object_195.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_196">
									<mesh
										name="Object_197"
										castShadow
										receiveShadow
										geometry={nodes.Object_197.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_198">
									<mesh
										name="Object_199"
										castShadow
										receiveShadow
										geometry={nodes.Object_199.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_200">
									<mesh
										name="Object_201"
										castShadow
										receiveShadow
										geometry={nodes.Object_201.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_202">
									<mesh
										name="Object_203"
										castShadow
										receiveShadow
										geometry={nodes.Object_203.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_204">
									<mesh
										name="Object_205"
										castShadow
										receiveShadow
										geometry={nodes.Object_205.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_206">
									<mesh
										name="Object_207"
										castShadow
										receiveShadow
										geometry={nodes.Object_207.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_208">
									<mesh
										name="Object_209"
										castShadow
										receiveShadow
										geometry={nodes.Object_209.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_210">
									<mesh
										name="Object_211"
										castShadow
										receiveShadow
										geometry={nodes.Object_211.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_212">
									<mesh
										name="Object_213"
										castShadow
										receiveShadow
										geometry={nodes.Object_213.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_214">
									<mesh
										name="Object_215"
										castShadow
										receiveShadow
										geometry={nodes.Object_215.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_216">
									<mesh
										name="Object_217"
										castShadow
										receiveShadow
										geometry={nodes.Object_217.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_218">
									<mesh
										name="Object_219"
										castShadow
										receiveShadow
										geometry={nodes.Object_219.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_220">
									<mesh
										name="Object_221"
										castShadow
										receiveShadow
										geometry={nodes.Object_221.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_222" scale={0}>
							<group name="frame_8">
								<group name="Object_224">
									<mesh
										name="Object_225"
										castShadow
										receiveShadow
										geometry={nodes.Object_225.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_226">
									<mesh
										name="Object_227"
										castShadow
										receiveShadow
										geometry={nodes.Object_227.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_228">
									<mesh
										name="Object_229"
										castShadow
										receiveShadow
										geometry={nodes.Object_229.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_230">
									<mesh
										name="Object_231"
										castShadow
										receiveShadow
										geometry={nodes.Object_231.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_232">
									<mesh
										name="Object_233"
										castShadow
										receiveShadow
										geometry={nodes.Object_233.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_234">
									<mesh
										name="Object_235"
										castShadow
										receiveShadow
										geometry={nodes.Object_235.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_236">
									<mesh
										name="Object_237"
										castShadow
										receiveShadow
										geometry={nodes.Object_237.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_238">
									<mesh
										name="Object_239"
										castShadow
										receiveShadow
										geometry={nodes.Object_239.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_240">
									<mesh
										name="Object_241"
										castShadow
										receiveShadow
										geometry={nodes.Object_241.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_242">
									<mesh
										name="Object_243"
										castShadow
										receiveShadow
										geometry={nodes.Object_243.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_244">
									<mesh
										name="Object_245"
										castShadow
										receiveShadow
										geometry={nodes.Object_245.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_246">
									<mesh
										name="Object_247"
										castShadow
										receiveShadow
										geometry={nodes.Object_247.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_248">
									<mesh
										name="Object_249"
										castShadow
										receiveShadow
										geometry={nodes.Object_249.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_250">
									<mesh
										name="Object_251"
										castShadow
										receiveShadow
										geometry={nodes.Object_251.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_252">
									<mesh
										name="Object_253"
										castShadow
										receiveShadow
										geometry={nodes.Object_253.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_254">
									<mesh
										name="Object_255"
										castShadow
										receiveShadow
										geometry={nodes.Object_255.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_256">
									<mesh
										name="Object_257"
										castShadow
										receiveShadow
										geometry={nodes.Object_257.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_258">
									<mesh
										name="Object_259"
										castShadow
										receiveShadow
										geometry={nodes.Object_259.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_260">
									<mesh
										name="Object_261"
										castShadow
										receiveShadow
										geometry={nodes.Object_261.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_262">
									<mesh
										name="Object_263"
										castShadow
										receiveShadow
										geometry={nodes.Object_263.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_264">
									<mesh
										name="Object_265"
										castShadow
										receiveShadow
										geometry={nodes.Object_265.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_266" scale={0}>
							<group name="frame_7">
								<group name="Object_268">
									<mesh
										name="Object_269"
										castShadow
										receiveShadow
										geometry={nodes.Object_269.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_270">
									<mesh
										name="Object_271"
										castShadow
										receiveShadow
										geometry={nodes.Object_271.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_272">
									<mesh
										name="Object_273"
										castShadow
										receiveShadow
										geometry={nodes.Object_273.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_274">
									<mesh
										name="Object_275"
										castShadow
										receiveShadow
										geometry={nodes.Object_275.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_276">
									<mesh
										name="Object_277"
										castShadow
										receiveShadow
										geometry={nodes.Object_277.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_278">
									<mesh
										name="Object_279"
										castShadow
										receiveShadow
										geometry={nodes.Object_279.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_280">
									<mesh
										name="Object_281"
										castShadow
										receiveShadow
										geometry={nodes.Object_281.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_282">
									<mesh
										name="Object_283"
										castShadow
										receiveShadow
										geometry={nodes.Object_283.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_284">
									<mesh
										name="Object_285"
										castShadow
										receiveShadow
										geometry={nodes.Object_285.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_286">
									<mesh
										name="Object_287"
										castShadow
										receiveShadow
										geometry={nodes.Object_287.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_288">
									<mesh
										name="Object_289"
										castShadow
										receiveShadow
										geometry={nodes.Object_289.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_290">
									<mesh
										name="Object_291"
										castShadow
										receiveShadow
										geometry={nodes.Object_291.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_292">
									<mesh
										name="Object_293"
										castShadow
										receiveShadow
										geometry={nodes.Object_293.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_294">
									<mesh
										name="Object_295"
										castShadow
										receiveShadow
										geometry={nodes.Object_295.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_296">
									<mesh
										name="Object_297"
										castShadow
										receiveShadow
										geometry={nodes.Object_297.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_298">
									<mesh
										name="Object_299"
										castShadow
										receiveShadow
										geometry={nodes.Object_299.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_300">
									<mesh
										name="Object_301"
										castShadow
										receiveShadow
										geometry={nodes.Object_301.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_302">
									<mesh
										name="Object_303"
										castShadow
										receiveShadow
										geometry={nodes.Object_303.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_304">
									<mesh
										name="Object_305"
										castShadow
										receiveShadow
										geometry={nodes.Object_305.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_306">
									<mesh
										name="Object_307"
										castShadow
										receiveShadow
										geometry={nodes.Object_307.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_308">
									<mesh
										name="Object_309"
										castShadow
										receiveShadow
										geometry={nodes.Object_309.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_310" scale={0}>
							<group name="frame_6">
								<group name="Object_312">
									<mesh
										name="Object_313"
										castShadow
										receiveShadow
										geometry={nodes.Object_313.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_314">
									<mesh
										name="Object_315"
										castShadow
										receiveShadow
										geometry={nodes.Object_315.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_316">
									<mesh
										name="Object_317"
										castShadow
										receiveShadow
										geometry={nodes.Object_317.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_318">
									<mesh
										name="Object_319"
										castShadow
										receiveShadow
										geometry={nodes.Object_319.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_320">
									<mesh
										name="Object_321"
										castShadow
										receiveShadow
										geometry={nodes.Object_321.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_322">
									<mesh
										name="Object_323"
										castShadow
										receiveShadow
										geometry={nodes.Object_323.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_324">
									<mesh
										name="Object_325"
										castShadow
										receiveShadow
										geometry={nodes.Object_325.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_326">
									<mesh
										name="Object_327"
										castShadow
										receiveShadow
										geometry={nodes.Object_327.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_328">
									<mesh
										name="Object_329"
										castShadow
										receiveShadow
										geometry={nodes.Object_329.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_330">
									<mesh
										name="Object_331"
										castShadow
										receiveShadow
										geometry={nodes.Object_331.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_332">
									<mesh
										name="Object_333"
										castShadow
										receiveShadow
										geometry={nodes.Object_333.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_334">
									<mesh
										name="Object_335"
										castShadow
										receiveShadow
										geometry={nodes.Object_335.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_336">
									<mesh
										name="Object_337"
										castShadow
										receiveShadow
										geometry={nodes.Object_337.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_338">
									<mesh
										name="Object_339"
										castShadow
										receiveShadow
										geometry={nodes.Object_339.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_340">
									<mesh
										name="Object_341"
										castShadow
										receiveShadow
										geometry={nodes.Object_341.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_342">
									<mesh
										name="Object_343"
										castShadow
										receiveShadow
										geometry={nodes.Object_343.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_344">
									<mesh
										name="Object_345"
										castShadow
										receiveShadow
										geometry={nodes.Object_345.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_346">
									<mesh
										name="Object_347"
										castShadow
										receiveShadow
										geometry={nodes.Object_347.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_348">
									<mesh
										name="Object_349"
										castShadow
										receiveShadow
										geometry={nodes.Object_349.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_350">
									<mesh
										name="Object_351"
										castShadow
										receiveShadow
										geometry={nodes.Object_351.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_352">
									<mesh
										name="Object_353"
										castShadow
										receiveShadow
										geometry={nodes.Object_353.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_354" scale={0}>
							<group name="frame_5">
								<group name="Object_356">
									<mesh
										name="Object_357"
										castShadow
										receiveShadow
										geometry={nodes.Object_357.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_358">
									<mesh
										name="Object_359"
										castShadow
										receiveShadow
										geometry={nodes.Object_359.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_360">
									<mesh
										name="Object_361"
										castShadow
										receiveShadow
										geometry={nodes.Object_361.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_362">
									<mesh
										name="Object_363"
										castShadow
										receiveShadow
										geometry={nodes.Object_363.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_364">
									<mesh
										name="Object_365"
										castShadow
										receiveShadow
										geometry={nodes.Object_365.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_366">
									<mesh
										name="Object_367"
										castShadow
										receiveShadow
										geometry={nodes.Object_367.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_368">
									<mesh
										name="Object_369"
										castShadow
										receiveShadow
										geometry={nodes.Object_369.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_370">
									<mesh
										name="Object_371"
										castShadow
										receiveShadow
										geometry={nodes.Object_371.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_372">
									<mesh
										name="Object_373"
										castShadow
										receiveShadow
										geometry={nodes.Object_373.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_374">
									<mesh
										name="Object_375"
										castShadow
										receiveShadow
										geometry={nodes.Object_375.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_376">
									<mesh
										name="Object_377"
										castShadow
										receiveShadow
										geometry={nodes.Object_377.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_378">
									<mesh
										name="Object_379"
										castShadow
										receiveShadow
										geometry={nodes.Object_379.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_380">
									<mesh
										name="Object_381"
										castShadow
										receiveShadow
										geometry={nodes.Object_381.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_382">
									<mesh
										name="Object_383"
										castShadow
										receiveShadow
										geometry={nodes.Object_383.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_384">
									<mesh
										name="Object_385"
										castShadow
										receiveShadow
										geometry={nodes.Object_385.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_386">
									<mesh
										name="Object_387"
										castShadow
										receiveShadow
										geometry={nodes.Object_387.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_388">
									<mesh
										name="Object_389"
										castShadow
										receiveShadow
										geometry={nodes.Object_389.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_390">
									<mesh
										name="Object_391"
										castShadow
										receiveShadow
										geometry={nodes.Object_391.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_392">
									<mesh
										name="Object_393"
										castShadow
										receiveShadow
										geometry={nodes.Object_393.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_394">
									<mesh
										name="Object_395"
										castShadow
										receiveShadow
										geometry={nodes.Object_395.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_396">
									<mesh
										name="Object_397"
										castShadow
										receiveShadow
										geometry={nodes.Object_397.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_398" scale={0}>
							<group name="frame_4">
								<group name="Object_400">
									<mesh
										name="Object_401"
										castShadow
										receiveShadow
										geometry={nodes.Object_401.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_402">
									<mesh
										name="Object_403"
										castShadow
										receiveShadow
										geometry={nodes.Object_403.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_404">
									<mesh
										name="Object_405"
										castShadow
										receiveShadow
										geometry={nodes.Object_405.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_406">
									<mesh
										name="Object_407"
										castShadow
										receiveShadow
										geometry={nodes.Object_407.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_408">
									<mesh
										name="Object_409"
										castShadow
										receiveShadow
										geometry={nodes.Object_409.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_410">
									<mesh
										name="Object_411"
										castShadow
										receiveShadow
										geometry={nodes.Object_411.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_412">
									<mesh
										name="Object_413"
										castShadow
										receiveShadow
										geometry={nodes.Object_413.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_414">
									<mesh
										name="Object_415"
										castShadow
										receiveShadow
										geometry={nodes.Object_415.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_416">
									<mesh
										name="Object_417"
										castShadow
										receiveShadow
										geometry={nodes.Object_417.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_418">
									<mesh
										name="Object_419"
										castShadow
										receiveShadow
										geometry={nodes.Object_419.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_420">
									<mesh
										name="Object_421"
										castShadow
										receiveShadow
										geometry={nodes.Object_421.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_422">
									<mesh
										name="Object_423"
										castShadow
										receiveShadow
										geometry={nodes.Object_423.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_424">
									<mesh
										name="Object_425"
										castShadow
										receiveShadow
										geometry={nodes.Object_425.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_426">
									<mesh
										name="Object_427"
										castShadow
										receiveShadow
										geometry={nodes.Object_427.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_428">
									<mesh
										name="Object_429"
										castShadow
										receiveShadow
										geometry={nodes.Object_429.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_430">
									<mesh
										name="Object_431"
										castShadow
										receiveShadow
										geometry={nodes.Object_431.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_432">
									<mesh
										name="Object_433"
										castShadow
										receiveShadow
										geometry={nodes.Object_433.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_434">
									<mesh
										name="Object_435"
										castShadow
										receiveShadow
										geometry={nodes.Object_435.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_436">
									<mesh
										name="Object_437"
										castShadow
										receiveShadow
										geometry={nodes.Object_437.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_438">
									<mesh
										name="Object_439"
										castShadow
										receiveShadow
										geometry={nodes.Object_439.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_440">
									<mesh
										name="Object_441"
										castShadow
										receiveShadow
										geometry={nodes.Object_441.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_442" scale={0}>
							<group name="frame_3">
								<group name="Object_444">
									<mesh
										name="Object_445"
										castShadow
										receiveShadow
										geometry={nodes.Object_445.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_446">
									<mesh
										name="Object_447"
										castShadow
										receiveShadow
										geometry={nodes.Object_447.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_448">
									<mesh
										name="Object_449"
										castShadow
										receiveShadow
										geometry={nodes.Object_449.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_450">
									<mesh
										name="Object_451"
										castShadow
										receiveShadow
										geometry={nodes.Object_451.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_452">
									<mesh
										name="Object_453"
										castShadow
										receiveShadow
										geometry={nodes.Object_453.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_454">
									<mesh
										name="Object_455"
										castShadow
										receiveShadow
										geometry={nodes.Object_455.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_456">
									<mesh
										name="Object_457"
										castShadow
										receiveShadow
										geometry={nodes.Object_457.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_458">
									<mesh
										name="Object_459"
										castShadow
										receiveShadow
										geometry={nodes.Object_459.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_460">
									<mesh
										name="Object_461"
										castShadow
										receiveShadow
										geometry={nodes.Object_461.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_462">
									<mesh
										name="Object_463"
										castShadow
										receiveShadow
										geometry={nodes.Object_463.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_464">
									<mesh
										name="Object_465"
										castShadow
										receiveShadow
										geometry={nodes.Object_465.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_466">
									<mesh
										name="Object_467"
										castShadow
										receiveShadow
										geometry={nodes.Object_467.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_468">
									<mesh
										name="Object_469"
										castShadow
										receiveShadow
										geometry={nodes.Object_469.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_470">
									<mesh
										name="Object_471"
										castShadow
										receiveShadow
										geometry={nodes.Object_471.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_472">
									<mesh
										name="Object_473"
										castShadow
										receiveShadow
										geometry={nodes.Object_473.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_474">
									<mesh
										name="Object_475"
										castShadow
										receiveShadow
										geometry={nodes.Object_475.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_476">
									<mesh
										name="Object_477"
										castShadow
										receiveShadow
										geometry={nodes.Object_477.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_478">
									<mesh
										name="Object_479"
										castShadow
										receiveShadow
										geometry={nodes.Object_479.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_480">
									<mesh
										name="Object_481"
										castShadow
										receiveShadow
										geometry={nodes.Object_481.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_482">
									<mesh
										name="Object_483"
										castShadow
										receiveShadow
										geometry={nodes.Object_483.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_484">
									<mesh
										name="Object_485"
										castShadow
										receiveShadow
										geometry={nodes.Object_485.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_486" scale={0}>
							<group name="frame_2">
								<group name="Object_488">
									<mesh
										name="Object_489"
										castShadow
										receiveShadow
										geometry={nodes.Object_489.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_490">
									<mesh
										name="Object_491"
										castShadow
										receiveShadow
										geometry={nodes.Object_491.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_492">
									<mesh
										name="Object_493"
										castShadow
										receiveShadow
										geometry={nodes.Object_493.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_494">
									<mesh
										name="Object_495"
										castShadow
										receiveShadow
										geometry={nodes.Object_495.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_496">
									<mesh
										name="Object_497"
										castShadow
										receiveShadow
										geometry={nodes.Object_497.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_498">
									<mesh
										name="Object_499"
										castShadow
										receiveShadow
										geometry={nodes.Object_499.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_500">
									<mesh
										name="Object_501"
										castShadow
										receiveShadow
										geometry={nodes.Object_501.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_502">
									<mesh
										name="Object_503"
										castShadow
										receiveShadow
										geometry={nodes.Object_503.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_504">
									<mesh
										name="Object_505"
										castShadow
										receiveShadow
										geometry={nodes.Object_505.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_506">
									<mesh
										name="Object_507"
										castShadow
										receiveShadow
										geometry={nodes.Object_507.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_508">
									<mesh
										name="Object_509"
										castShadow
										receiveShadow
										geometry={nodes.Object_509.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_510">
									<mesh
										name="Object_511"
										castShadow
										receiveShadow
										geometry={nodes.Object_511.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_512">
									<mesh
										name="Object_513"
										castShadow
										receiveShadow
										geometry={nodes.Object_513.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_514">
									<mesh
										name="Object_515"
										castShadow
										receiveShadow
										geometry={nodes.Object_515.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_516">
									<mesh
										name="Object_517"
										castShadow
										receiveShadow
										geometry={nodes.Object_517.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_518">
									<mesh
										name="Object_519"
										castShadow
										receiveShadow
										geometry={nodes.Object_519.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_520">
									<mesh
										name="Object_521"
										castShadow
										receiveShadow
										geometry={nodes.Object_521.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_522">
									<mesh
										name="Object_523"
										castShadow
										receiveShadow
										geometry={nodes.Object_523.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_524">
									<mesh
										name="Object_525"
										castShadow
										receiveShadow
										geometry={nodes.Object_525.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_526">
									<mesh
										name="Object_527"
										castShadow
										receiveShadow
										geometry={nodes.Object_527.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_528">
									<mesh
										name="Object_529"
										castShadow
										receiveShadow
										geometry={nodes.Object_529.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_530" scale={0}>
							<group name="frame_1">
								<group name="Object_532">
									<mesh
										name="Object_533"
										castShadow
										receiveShadow
										geometry={nodes.Object_533.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_534">
									<mesh
										name="Object_535"
										castShadow
										receiveShadow
										geometry={nodes.Object_535.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_536">
									<mesh
										name="Object_537"
										castShadow
										receiveShadow
										geometry={nodes.Object_537.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_538">
									<mesh
										name="Object_539"
										castShadow
										receiveShadow
										geometry={nodes.Object_539.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_540">
									<mesh
										name="Object_541"
										castShadow
										receiveShadow
										geometry={nodes.Object_541.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_542">
									<mesh
										name="Object_543"
										castShadow
										receiveShadow
										geometry={nodes.Object_543.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_544">
									<mesh
										name="Object_545"
										castShadow
										receiveShadow
										geometry={nodes.Object_545.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_546">
									<mesh
										name="Object_547"
										castShadow
										receiveShadow
										geometry={nodes.Object_547.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_548">
									<mesh
										name="Object_549"
										castShadow
										receiveShadow
										geometry={nodes.Object_549.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_550">
									<mesh
										name="Object_551"
										castShadow
										receiveShadow
										geometry={nodes.Object_551.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_552">
									<mesh
										name="Object_553"
										castShadow
										receiveShadow
										geometry={nodes.Object_553.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_554">
									<mesh
										name="Object_555"
										castShadow
										receiveShadow
										geometry={nodes.Object_555.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_556">
									<mesh
										name="Object_557"
										castShadow
										receiveShadow
										geometry={nodes.Object_557.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_558">
									<mesh
										name="Object_559"
										castShadow
										receiveShadow
										geometry={nodes.Object_559.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_560">
									<mesh
										name="Object_561"
										castShadow
										receiveShadow
										geometry={nodes.Object_561.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_562">
									<mesh
										name="Object_563"
										castShadow
										receiveShadow
										geometry={nodes.Object_563.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_564">
									<mesh
										name="Object_565"
										castShadow
										receiveShadow
										geometry={nodes.Object_565.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_566">
									<mesh
										name="Object_567"
										castShadow
										receiveShadow
										geometry={nodes.Object_567.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_568">
									<mesh
										name="Object_569"
										castShadow
										receiveShadow
										geometry={nodes.Object_569.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_570">
									<mesh
										name="Object_571"
										castShadow
										receiveShadow
										geometry={nodes.Object_571.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_572">
									<mesh
										name="Object_573"
										castShadow
										receiveShadow
										geometry={nodes.Object_573.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
						<group name="Object_574">
							<group name="frame_0">
								<group name="Object_576">
									<mesh
										name="Object_577"
										castShadow
										receiveShadow
										geometry={nodes.Object_577.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_578">
									<mesh
										name="Object_579"
										castShadow
										receiveShadow
										geometry={nodes.Object_579.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_580">
									<mesh
										name="Object_581"
										castShadow
										receiveShadow
										geometry={nodes.Object_581.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_582">
									<mesh
										name="Object_583"
										castShadow
										receiveShadow
										geometry={nodes.Object_583.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_584">
									<mesh
										name="Object_585"
										castShadow
										receiveShadow
										geometry={nodes.Object_585.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_586">
									<mesh
										name="Object_587"
										castShadow
										receiveShadow
										geometry={nodes.Object_587.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_588">
									<mesh
										name="Object_589"
										castShadow
										receiveShadow
										geometry={nodes.Object_589.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_590">
									<mesh
										name="Object_591"
										castShadow
										receiveShadow
										geometry={nodes.Object_591.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_592">
									<mesh
										name="Object_593"
										castShadow
										receiveShadow
										geometry={nodes.Object_593.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_594">
									<mesh
										name="Object_595"
										castShadow
										receiveShadow
										geometry={nodes.Object_595.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_596">
									<mesh
										name="Object_597"
										castShadow
										receiveShadow
										geometry={nodes.Object_597.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_598">
									<mesh
										name="Object_599"
										castShadow
										receiveShadow
										geometry={nodes.Object_599.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_600">
									<mesh
										name="Object_601"
										castShadow
										receiveShadow
										geometry={nodes.Object_601.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_602">
									<mesh
										name="Object_603"
										castShadow
										receiveShadow
										geometry={nodes.Object_603.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_604">
									<mesh
										name="Object_605"
										castShadow
										receiveShadow
										geometry={nodes.Object_605.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_606">
									<mesh
										name="Object_607"
										castShadow
										receiveShadow
										geometry={nodes.Object_607.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_608">
									<mesh
										name="Object_609"
										castShadow
										receiveShadow
										geometry={nodes.Object_609.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_610">
									<mesh
										name="Object_611"
										castShadow
										receiveShadow
										geometry={nodes.Object_611.geometry}
										material={materials.Material0}
									/>
								</group>
								<group name="Object_612">
									<mesh
										name="Object_613"
										castShadow
										receiveShadow
										geometry={nodes.Object_613.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_614">
									<mesh
										name="Object_615"
										castShadow
										receiveShadow
										geometry={nodes.Object_615.geometry}
										material={materials.material_0}
									/>
								</group>
								<group name="Object_616">
									<mesh
										name="Object_617"
										castShadow
										receiveShadow
										geometry={nodes.Object_617.geometry}
										material={materials.material_0}
									/>
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
};

useGLTF.preload("/adventurers.glb");

export default AdventurersCamp;
